{
 "title": "MilvusStandalone",
 "tags": [ "milvus2.0" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "数据源", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Proxy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Search Vector Count Rate",
   "type": "timeseries",
   "description": "per-second increasing rate of searching vectors.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(milvus_proxy_search_vectors_count{}[2m])/120) by (pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Insert Vector Count Rate",
   "type": "timeseries",
   "description": "per-second increasing rate of inserting vectors.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(milvus_proxy_insert_vectors_count{}[2m])/120) by (pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Search Latency",
   "type": "timeseries",
   "description": "The 99th percentile and average latency of search request over the last 2 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, pod, node_id) (rate(milvus_proxy_sq_latency_bucket{}[2m])))",
     "legendFormat": "p99-{{pod}}-{{node_id}}"
    },
    {
     "expr": "sum(increase(milvus_proxy_sq_latency_sum{}[2m])) by (pod, node_id) / sum(increase(milvus_proxy_sq_latency_count{}[2m])) by (pod, node_id)",
     "legendFormat": "avg-{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Collection Search Latency",
   "type": "graph",
   "description": "The 99th percentile and average latency of search request for a specified collection over the last 2 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, pod, node_id) (rate(milvus_proxy_collection_sq_latency_bucket{}[2m])))",
     "legendFormat": "p99-{{pod}}-{{node_id}}"
    },
    {
     "expr": "sum(increase(milvus_proxy_collection_sq_latency_sum{}[2m])) by (pod, node_id) / sum(increase(milvus_proxy_collection_sq_latency_count{}[2m])) by (pod, node_id)",
     "legendFormat": "avg-{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Mutation Latency",
   "type": "graph",
   "description": "The 99th percentile and average latency of mutation request over the last 2 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, msg_type, pod, node_id) (rate(milvus_proxy_mutation_latency_bucket{}[2m])))",
     "legendFormat": "p99-{{msg_type}}-{{pod}}-{{node_id}}"
    },
    {
     "expr": "sum(increase(milvus_proxy_mutation_latency_sum{}[2m])) by (pod, node_id, msg_type) / sum(increase(milvus_proxy_mutation_latency_count{}[2m])) by (pod, node_id, msg_type)",
     "legendFormat": "avg-{{msg_type}}-{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Collection Mutation Latency",
   "type": "graph",
   "description": "The 99th percentile and average latency of mutation request for a specified collection over the last 2 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, msg_type, pod, node_id) (rate(milvus_proxy_collection_mutation_latency_bucket{}[2m])))",
     "legendFormat": "p99-{{pod}}-{{node_id}}-{{msg_type}}"
    },
    {
     "expr": "sum(increase(milvus_proxy_collection_mutation_latency_sum{}[2m])) by (pod, node_id, msg_type) / sum(increase(milvus_proxy_collection_mutation_latency_count{}[2m])) by (pod, node_id, msg_type)",
     "legendFormat": "avg-{{pod}}-{{node_id}}-{{msg_type}}"
    }
   ]
  },
  {
   "title": "Wait Search Result Latency",
   "type": "graph",
   "description": "The 99th percentile and average latency of wait search result over the last 2 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, pod, node_id) (rate(milvus_proxy_sq_wait_result_latency_bucket{}[2m])))",
     "legendFormat": "p99-{{pod}}-{{node_id}}"
    },
    {
     "expr": "sum(increase(milvus_proxy_sq_wait_result_latency_sum{}[2m])) by (pod, node_id) / sum(increase(milvus_proxy_sq_wait_result_latency_count{}[2m])) by (pod, node_id)",
     "legendFormat": "avg-{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Reduce Search Result Latency",
   "type": "graph",
   "description": "The 99th percentile and average latency of reduce search result over the last 2 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, pod, node_id) (rate(milvus_proxy_sq_reduce_result_latency_bucket{}[2m])))",
     "legendFormat": "p99-{{pod}}-{{node_id}}"
    },
    {
     "expr": "sum(increase(milvus_proxy_sq_reduce_result_latency_sum{}[2m])) by (pod, node_id) / sum(increase(milvus_proxy_sq_reduce_result_latency_count{}[2m])) by (pod, node_id)",
     "legendFormat": "avg-{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Decode Search Result Latency",
   "type": "graph",
   "description": "The 99th percentile and average latency of decode search result over the last 2 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, pod, node_id) (rate(milvus_proxy_sq_decode_result_latency_bucket{}[2m])))",
     "legendFormat": "p99-{{pod}}-{{node_id}}"
    },
    {
     "expr": "sum(increase(milvus_proxy_sq_decode_result_latency_sum{}[2m])) by (pod, node_id) / sum(increase(milvus_proxy_sq_decode_resultlatency_count{}[2m])) by (pod, node_id)",
     "legendFormat": "avg-{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Msg Stream Object Num",
   "type": "graph",
   "description": "Average, maximum and minimum values of the number of msgstream objects created on all physical topics.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(milvus_proxy_msgstream_obj_num{}) by (pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}-avg"
    },
    {
     "expr": "max(milvus_proxy_msgstream_obj_num{}) by (pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}-max"
    },
    {
     "expr": "min(milvus_proxy_msgstream_obj_num{}) by (pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}-min"
    }
   ]
  },
  {
   "title": "Mutation Send Latency",
   "type": "graph",
   "description": "The 99th percentile and average latency of send mutation over the last 2 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, msg_type, pod, node_id) (rate(milvus_proxy_mutation_send_latency_bucket{}[2m])))",
     "legendFormat": "p99-{{msg_type}}-{{pod}}-{{node_id}}"
    },
    {
     "expr": "sum(increase(milvus_proxy_mutation_latency_sum{}[2m])) by (pod, node_id, msg_type) / sum(increase(milvus_proxy_mutation_latency_count{}[2m])) by (pod, node_id, msg_type)",
     "legendFormat": "avg-{{msg_type}}-{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Cache Hit rate",
   "type": "graph",
   "description": "Average cache hits per minute of cache operations.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(milvus_proxy_cache_hit_count{cache_state=\"hit\"}[2m])/120) by(cache_name, pod, node_id) / sum(increase(milvus_proxy_cache_hit_count{}[2m])/120) by(cache_name, pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}-{{cache_name}}"
    }
   ]
  },
  {
   "title": "Cache Update Latency",
   "type": "graph",
   "description": "The 99th percentile and average latency of update cache over the last 2 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, pod, node_id) (rate(milvus_proxy_cache_update_latency_bucket{}[2m])))",
     "legendFormat": "p99-{{pod}}-{{node_id}}"
    },
    {
     "expr": "sum(increase(milvus_proxy_cache_update_latency_sum{}[2m])) by (pod, node_id) / sum(increase(milvus_proxy_cache_update_latency_count{}[2m])) by (pod, node_id)",
     "legendFormat": "avg-{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Produced Timetick Lag Behind Now",
   "type": "graph",
   "description": "Average, maximum and minimum values of the  timestamps for time tick behind.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(milvus_proxy_tt_lag_ms{}) by (pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}-avg"
    },
    {
     "expr": "max(milvus_proxy_tt_lag_ms{}) by (pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}-max"
    },
    {
     "expr": "min(milvus_proxy_tt_lag_ms{}) by (pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}-min"
    },
    {}
   ]
  },
  {
   "title": "Apply PK Latency",
   "type": "graph",
   "description": "The 99th percentile of latency for applying PK over the last 2 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, pod, node_id) (rate(milvus_proxy_apply_pk_latency_bucket{}[2m])))",
     "legendFormat": "p99-{{pod}}-{{node_id}}"
    },
    {
     "expr": "sum(increase(milvus_proxy_apply_pk_latency_sum{}[2m])) by (pod, node_id) / sum(increase(milvus_proxy_apply_pk_latency_count{}[2m])) by (pod, node_id)",
     "legendFormat": "avg-{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Apply Timestamp Latency",
   "type": "graph",
   "description": "The 99th percentile and average latency of apply timestamp over the last 2 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, pod, node_id) (rate(milvus_proxy_apply_timestamp_latency_bucket{}[2m])))",
     "legendFormat": "p99-{{pod}}-{{node_id}}"
    },
    {
     "expr": "sum(increase(milvus_proxy_apply_timestamp_latency_sum{}[2m])) by (pod, node_id) / sum(increase(milvus_proxy_apply_timestamp_latency_count{}[2m])) by (pod, node_id)",
     "legendFormat": "avg-{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Success Request Rate",
   "type": "graph",
   "description": "per-second increasing rate of success requests.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(milvus_proxy_req_count{status=\"success\"}[2m])/120) by(function_name, pod, node_id)",
     "legendFormat": "{{function_name}}-{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Faild Request Rate",
   "type": "graph",
   "description": "per-second increasing rate of faild requests.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(milvus_proxy_req_count{status=\"fail\"}[2m])/120) by(function_name, pod, node_id)",
     "legendFormat": "{{function_name}}-{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "graph",
   "description": "The 99th percentile and average latency of request over the last 2 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, pod, node_id, function_name) (rate(milvus_proxy_req_latency_bucket{}[2m])))",
     "legendFormat": "p99-{{function_name}}-{{pod}}-{{node_id}}"
    },
    {
     "expr": "sum(increase(milvus_proxy_req_latency_sum{}[2m])) by (pod, node_id, function_name) / sum(increase(milvus_proxy_req_latency_count{}[2m])) by (pod, node_id, function_name)",
     "legendFormat": "avg-{{function_name}}-{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Received Byte Rate",
   "type": "graph",
   "description": "per-second increasing rate of bytes received  in proxy",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(milvus_proxy_receive_bytes_count{}[2m])/120) by(pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Send Byte Rate",
   "type": "graph",
   "description": "per-second increasing rate of bytes sent back to the client by the Proxy in response to a Search or Query request.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(milvus_proxy_send_bytes_count{}[2m])/120) by(pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Root Coordinator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Proxy Node Num",
     "type": "graph",
     "description": "Number of proxy nodes which has register with etcd",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(milvus_rootcoord_proxy_num{}) by (app_kubernetes_io_instance)",
       "legendFormat": "num"
      }
     ]
    },
    {
     "title": "Produced Timetick Lag Behind Now",
     "type": "graph",
     "description": "Average, maximum and minimum values of the  timestamps for time tick behind.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg(milvus_rootcoord_produce_tt_lag_ms{}) by (pod, node_id)",
       "legendFormat": "{{pod}}-{{node_id}}-avg"
      },
      {
       "expr": "max(milvus_rootcoord_produce_tt_lag_ms{}) by (pod, node_id)",
       "legendFormat": "{{pod}}-{{node_id}}-max"
      },
      {
       "expr": "min(milvus_rootcoord_produce_tt_lag_ms{}) by (pod, node_id)",
       "legendFormat": "{{pod}}-{{node_id}}-min"
      }
     ]
    },
    {
     "title": "Produced Timetick Time Taken",
     "type": "graph",
     "description": "The 99th percentile and average latency for rootcoord to finish synchronizing timestamp messages to all pchanels.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(milvus_rootcoord_sync_timetick_latency_bucket{}[2m])))",
       "legendFormat": "p99-latency"
      },
      {
       "expr": "sum(increase(milvus_rootcoord_sync_timetick_latency_sum{}[2m])) / sum(increase(milvus_rootcoord_sync_timetick_latency_count{}[2m]))",
       "legendFormat": "avg-latency"
      }
     ]
    },
    {
     "title": "DDL Request Latency",
     "type": "graph",
     "description": "The 99th percentile and average latency of DDL request over the last 2 minutes.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le, function_name) (rate(milvus_rootcoord_ddl_req_latency_bucket{}[2m])))",
       "legendFormat": "p99-{{function_name}}"
      },
      {
       "expr": "sum(increase(milvus_rootcoord_ddl_req_latency_sum{}[2m])) by (function_name) / sum(increase(milvus_rootcoord_ddl_req_latency_count{}[2m])) by (function_name)",
       "legendFormat": "avg-{{function_name}}"
      }
     ]
    },
    {
     "title": "Timestamp Saved",
     "type": "graph",
     "description": "RootCoord stores pre-assigned timestamps in the metastore",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "milvus_rootcoord_timestamp_saved{}",
       "legendFormat": "tiestamp"
      }
     ]
    },
    {
     "title": "DDL Request Rate",
     "type": "graph",
     "description": "per-second increasing rate of DDL request",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(milvus_rootcoord_ddl_req_count{}[2m])/120) by (status, function_name)",
       "legendFormat": "{{function_name}}-{{status}}"
      }
     ]
    },
    {
     "title": "Timestamp",
     "type": "graph",
     "description": "RoootCoord current latest timestamp",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "milvus_rootcoord_timestamp{}", "legendFormat": "tiestamp" }
     ]
    },
    {
     "title": "DML Channel Num",
     "type": "graph",
     "description": "The number of DML channels",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(milvus_rootcoord_dml_channel_num{}) by (app_kubernetes_io_instance)",
       "legendFormat": "num"
      }
     ]
    },
    {
     "title": "ID Alloc Rate",
     "type": "graph",
     "description": "per-second increasing rate of IDs assigned by RootCoord",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(milvus_rootcoord_id_alloc_count{}[2m])/120)",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Partition Num",
     "type": "graph",
     "description": "The number of partitions.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(milvus_rootcoord_partition_num{}) by (app_kubernetes_io_instance)",
       "legendFormat": "num"
      }
     ]
    },
    {
     "title": "Time Tick Delay",
     "type": "graph",
     "description": "The max time tick delay of flow graphs. unit ms",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(milvus_rootcoord_time_tick_delay{}) by (role_name, node_id)",
       "legendFormat": "{{role_name}}-{{node_id}}"
      }
     ]
    },
    {
     "title": "Collection Num",
     "type": "graph",
     "description": "The number of collections.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(milvus_rootcoord_collection_num{}) by (app_kubernetes_io_instance)",
       "legendFormat": "num"
      }
     ]
    },
    {
     "title": "Credential Num",
     "type": "graph",
     "description": "The number of credential",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(milvus_rootcoord_credential_num{}) by (app_kubernetes_io_instance)",
       "legendFormat": "num"
      }
     ]
    },
    {
     "title": "Msgstream Num",
     "type": "graph",
     "description": "The number of Msgstream objects.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(milvus_rootcoord_msgstream_obj_num{}) by (app_kubernetes_io_instance)",
       "legendFormat": "num"
      }
     ]
    }
   ]
  },
  {
   "title": "Query Coordinator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Collection Loaded Num",
     "type": "graph",
     "description": "Total number of loaded collections.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(milvus_querycoord_collection_num{}) by (app_kubernetes_io_instance)",
       "legendFormat": "num"
      }
     ]
    },
    {
     "title": "Entity Loaded Num",
     "type": "graph",
     "description": "Total number of loaded entities.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(milvus_querycoord_entity_num{}) by (app_kubernetes_io_instance)",
       "legendFormat": "num"
      }
     ]
    },
    {
     "title": "Load Request Rate",
     "type": "graph",
     "description": "per-second increasing rate of load requests.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(milvus_querycoord_load_req_count{}[2m])/120) by (status)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Release Request Rate",
     "type": "graph",
     "description": "per-second increasing rate of relaase requests.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(milvus_querycoord_release_req_count{}[2m])/120) by (status)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Load Request Latency",
     "type": "graph",
     "description": "The 99th percentile and average latency of load request over the last 2 minutes.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(milvus_querycoord_load_latency_bucket{}[2m])))",
       "legendFormat": "p99-latency"
      },
      {
       "expr": "sum(increase(milvus_querycoord_load_latency_sum{}[2m])) / sum(increase(milvus_querycoord_load_latency_count{}[2m]))",
       "legendFormat": "avg-latency"
      }
     ]
    },
    {
     "title": "Release Request Latency",
     "type": "graph",
     "description": "The 99th percentile and average latency of release request over the last 2 minutes.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(milvus_querycoord_release_latency_bucket{}[2m])))",
       "legendFormat": "p99-latency"
      },
      {
       "expr": "sum(increase(milvus_querycoord_release_latency_sum{}[2m])) / sum(increase(milvus_querycoord_release_latency_count{}[2m]))",
       "legendFormat": "avg-latency"
      }
     ]
    },
    {
     "title": "Sub-Load Task",
     "type": "graph",
     "description": "Total number of sub-load task.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(milvus_querycoord_child_task_num{}) by (app_kubernetes_io_instance)",
       "legendFormat": "num"
      }
     ]
    },
    {
     "title": "Parent Load Task",
     "type": "graph",
     "description": "Total number pf parent loading task.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(milvus_querycoord_parent_task_num{}) by (app_kubernetes_io_instance)",
       "legendFormat": "num"
      }
     ]
    },
    {
     "title": "Sub-Load Task Latency",
     "type": "graph",
     "description": "The 99th percentile and average latency of sub-load task request over the last 2 minutes.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(milvus_querycoord_child_task_latency_bucket{}[2m])))",
       "legendFormat": "p99-latency"
      },
      {
       "expr": "sum(increase(milvus_querycoord_child_task_latency_sum{}[2m])) / sum(increase(milvus_querycoord_child_task_latency_count{}[2m]))",
       "legendFormat": "avg-latency"
      }
     ]
    },
    {
     "title": "Query Node Num",
     "type": "graph",
     "description": "Number of Query nodes which has register with etcd.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(milvus_querycoord_querynode_num{}) by (app_kubernetes_io_instance)",
       "legendFormat": "num"
      }
     ]
    }
   ]
  },
  {
   "title": "Query Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Collection Loaded Num",
   "type": "graph",
   "description": "Total number of the loaded collections in QueryNode.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(milvus_querynode_collection_num{}) by (pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Partition Loaded Num",
   "type": "graph",
   "description": "Total number of the loaded partitions in QueryNode.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(milvus_querynode_partition_num{}) by (pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Segment Loaded Num",
   "type": "graph",
   "description": "Total number of the loaded segment in QueryNode.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(milvus_querynode_segment_num{}) by (pod, node_id, segment_state)",
     "legendFormat": "{{pod}}-{{node_id}}-{{segment_state}}"
    }
   ]
  },
  {
   "title": "TimeTick Lag Behind Now (Consumed Insert)",
   "type": "graph",
   "description": "Average, maximum and minimum values of the  timestamps for time tick behind.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(milvus_querynode_consume_tt_lag_ms{msg_type=\"insert\"}) by (pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}-avg"
    },
    {
     "expr": "max(milvus_querynode_consume_tt_lag_ms{msg_type=\"insert\"}) by (pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}-max"
    },
    {
     "expr": "min(milvus_querynode_consume_tt_lag_ms{msg_type=\"insert\"}) by (pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}-min"
    }
   ]
  },
  {
   "title": "TimeTick Lag Behind Now (Consumed Delete)",
   "type": "graph",
   "description": "Average, maximum and minimum values of the  timestamps for time tick behind.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 52 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(milvus_querynode_consume_tt_lag_ms{msg_type=\"delete\"}) by (pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}-avg"
    },
    {
     "expr": "max(milvus_querynode_consume_tt_lag_ms{msg_type=\"delete\"}) by (pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}-max"
    },
    {
     "expr": "min(milvus_querynode_consume_tt_lag_ms{msg_type=\"delete\"}) by (pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}-min"
    }
   ]
  },
  {
   "title": "Consumed Message Rate",
   "type": "graph",
   "description": "per-second increasing rate of consuming message",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(milvus_querynode_consume_msg_count{}[2m])/120) by (pod, node_id, msg_type)",
     "legendFormat": "{{pod}}-{{node_id}}-{{msg_type}}"
    },
    {
     "expr": "sum(increase(milvus_querynode_consume_msg_count{}[2m])/120) by (pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}-all"
    }
   ]
  },
  {
   "title": "Queryable Entity Num",
   "type": "graph",
   "description": "Total number of the queryable entities  in QueryNode.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(milvus_querynode_entity_num{}) by (pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "DML Virtual Channel",
   "type": "graph",
   "description": "Total number of dml virtual channels for QueryNode watch",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(milvus_querynode_dml_vchannel_num{}) by (pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Delta Virtual Channel",
   "type": "graph",
   "description": "Total number of delta virtual channels for QueryNode watch",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(milvus_querynode_delta_vchannel_num{}) by (pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Consumer Num",
   "type": "graph",
   "description": "Total number of consumers in the QueryNode.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(milvus_querynode_consumer_num{}) by (pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Search Request Rate",
   "type": "graph",
   "description": "per-second increasing rate of searching requests.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(milvus_querynode_sq_req_count{}[2m])/120) by (status, pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}-{{status}}"
    }
   ]
  },
  {
   "title": "Search Request Latency",
   "type": "graph",
   "description": "The 99th percentile and average latency of search and query request over the last 2 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, pod, node_id) (rate(milvus_querynode_sq_req_latency_bucket{}[2m])))",
     "legendFormat": "p99-{{pod}}-{{node_id}}"
    },
    {
     "expr": "sum(increase(milvus_querynode_sq_req_latency_sum{}[2m])) by(pod, node_id) / sum(increase(milvus_querynode_sq_req_latency_count{}[2m])) by(pod, node_id)",
     "legendFormat": "avg-{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Search in Queue Latency",
   "type": "graph",
   "description": "The 99th percentile and average latency of search or query in queue over the last 2 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, pod, node_id) (rate(milvus_querynode_sq_queue_latency_bucket{}[2m])))",
     "legendFormat": "p99-{{pod}}-{{node_id}}"
    },
    {
     "expr": "sum(increase(milvus_querynode_sq_queue_latency_sum{}[2m])) by(pod, node_id) / sum(increase(milvus_querynode_sq_queue_latency_count{}[2m])) by(pod, node_id)",
     "legendFormat": "avg-{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Search Segment Latency",
   "type": "graph",
   "description": "The 99th percentile and average latency of search segment over the last 2 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, pod, node_id, segment_state) (rate(milvus_querynode_sq_segment_latency_bucket{}[2m])))",
     "legendFormat": "p99-{{pod}}-{{node_id}}-{{segment_state}}"
    },
    {
     "expr": "sum(increase(milvus_querynode_sq_segment_latency_sum{}[2m])) by(pod, node_id, segment_state) / sum(increase(milvus_querynode_sq_segment_latency_count{}[2m])) by(pod, node_id, segment_state)",
     "legendFormat": "avg-{{pod}}-{{node_id}}_{{segment_state}}"
    }
   ]
  },
  {
   "title": "Segcore Request Latency",
   "type": "graph",
   "description": "The 99th percentile and average latency of search at the segcore step over the last 2 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, pod, node_id) (rate(milvus_querynode_sq_core_latency_bucket{}[2m])))",
     "legendFormat": "p99-{{pod}}-{{node_id}}"
    },
    {
     "expr": "sum(increase(milvus_querynode_sq_core_latency_sum{}[2m])) by(pod, node_id) / sum(increase(milvus_querynode_sq_core_latency_count{}[2m])) by(pod, node_id)",
     "legendFormat": "avg-{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Search Reduce Latency",
   "type": "graph",
   "description": "The 99th percentile and average latency of search or query reduce over the last 2 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, pod, node_id) (rate(milvus_querynode_sq_reduce_latency_bucket{}[2m])))",
     "legendFormat": "p99-{{pod}}-{{node_id}}"
    },
    {
     "expr": "sum(increase(milvus_querynode_sq_reduce_latency_sum{}[2m])) by(pod, node_id) / sum(increase(milvus_querynode_sq_reduce_latency_count{}[2m])) by(pod, node_id)",
     "legendFormat": "avg-{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Load Segment Latency",
   "type": "graph",
   "description": "The 99th percentile and average latency of load segment over the last 2 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, pod, node_id) (rate(milvus_querynode_load_segment_latency_bucket{}[2m])))",
     "legendFormat": "p99-{{pod}}-{{node_id}}"
    },
    {
     "expr": "sum(increase(milvus_querynode_load_segment_latency_sum{}[2m])) by(pod, node_id) / sum(increase(milvus_querynode_load_segment_latency_count{}[2m])) by(pod, node_id)",
     "legendFormat": "avg-{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Flowgraph Num",
   "type": "graph",
   "description": "Total number of flowgraph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(milvus_querynode_flowgraph_num{}) by (pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Unsolved Read Task Length",
   "type": "graph",
   "description": "The length of the task queue for unsolved read requests",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(milvus_querynode_read_task_unsolved_len{}) by (pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Ready Read Task Length",
   "type": "graph",
   "description": "The length of the task queue of read requests to be executed",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(milvus_querynode_read_task_ready_len{}) by (pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Parallel Read Task Num",
   "type": "graph",
   "description": "Number of read requests currently being executed in parallel",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(milvus_querynode_read_task_concurrency{}) by (pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Estimate CPU Usage",
   "type": "graph",
   "description": "cpu utilization under scheduler evaluation",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(milvus_querynode_estimate_cpu_usage{}) by (pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Search Group Size",
   "type": "graph",
   "description": "The number of original tasks contained in the merged search task",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, pod, node_id) (rate(milvus_querynode_search_group_size_bucket{}[2m])))",
     "legendFormat": "p99-{{pod}}-{{node_id}}"
    },
    {
     "expr": "sum(increase(milvus_querynode_search_group_size_sum{}[2m])) by(pod, node_id) / sum(increase(milvus_querynode_search_group_size_count{}[2m])) by(pod, node_id)",
     "legendFormat": "avg-{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Search NQ",
   "type": "graph",
   "description": "Number of queries for search requests",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, pod, node_id) (rate(milvus_querynode_search_nq_bucket{}[2m])))",
     "legendFormat": "p99-{{pod}}-{{node_id}}"
    },
    {
     "expr": "sum(increase(milvus_querynode_search_nq_sum{}[2m])) by(pod, node_id) / sum(increase(milvus_querynode_search_nq_count{}[2m])) by(pod, node_id)",
     "legendFormat": "avg-{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Search Group NQ",
   "type": "graph",
   "description": "Number of queries for the merged search requests",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, pod, node_id) (rate(milvus_querynode_search_group_nq_bucket{}[2m])))",
     "legendFormat": "p99-{{pod}}-{{node_id}}"
    },
    {
     "expr": "sum(increase(milvus_querynode_search_group_nq_sum{}[2m])) by(pod, node_id) / sum(increase(milvus_querynode_search_group_nq_count{}[2m])) by(pod, node_id)",
     "legendFormat": "avg-milvus_querynode_search_group_nq"
    }
   ]
  },
  {
   "title": "Search Top_K",
   "type": "graph",
   "description": "Top_K for search requests",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, pod, node_id) (rate(milvus_querynode_search_topk_bucket{}[2m])))",
     "legendFormat": "p99-{{pod}}-{{node_id}}"
    },
    {
     "expr": "sum(increase(milvus_querynode_search_topk_sum{}[2m])) by(pod, node_id) / sum(increase(milvus_querynode_search_topk_count{}[2m])) by(pod, node_id)",
     "legendFormat": "avg-{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Search Group Top_K",
   "type": "graph",
   "description": "Top_K for the merged search requests.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, pod, node_id) (rate(milvus_querynode_search_group_topk_bucket{}[2m])))",
     "legendFormat": "p99-{{pod}}-{{node_id}}"
    },
    {
     "expr": "sum(increase(milvus_querynode_search_group_topk_sum{}[2m])) by(pod, node_id) / sum(increase(milvus_querynode_search_group_topk_count{}[2m])) by(pod, node_id)",
     "legendFormat": "avg-{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Evicted Read Requests Rate",
   "type": "graph",
   "description": "per-second increasing rate of evicted read requests.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(milvus_querynode_read_evicted_count{}[2m])/120) by (pod, node_id)",
     "legendFormat": "{{pod}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Data Coordinator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Data Node Num",
     "type": "graph",
     "description": "Number of data nodes which has register with etcd.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(milvus_datacoord_datanode_num{}) by (app_kubernetes_io_instance)",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "TimeTick Lag Behind Now From DataNode",
     "type": "graph",
     "description": "Average, maximum and minimum values of the  timestamps for time tick lag behind now from datanode.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg(milvus_datacoord_consume_datanode_tt_lag_ms{msg_type=\"all\"}) by (pod, node_id)",
       "legendFormat": "{{pod}}-{{node_id}}-avg"
      },
      {
       "expr": "max(milvus_datacoord_consume_datanode_tt_lag_ms{msg_type=\"all\"}) by (pod, node_id)",
       "legendFormat": "{{pod}}-{{node_id}}-max"
      },
      {
       "expr": "min(milvus_datacoord_consume_datanode_tt_lag_ms{msg_type=\"all\"}) by (pod, node_id)",
       "legendFormat": "{{pod}}-{{node_id}}-min"
      }
     ]
    },
    {
     "title": "Stored Rows",
     "type": "graph",
     "description": "The number of rows of valid data accumulated in DataCoord that flushed.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(milvus_datacoord_stored_rows_num{}) by (app_kubernetes_io_instance)",
       "legendFormat": "row"
      }
     ]
    },
    {
     "title": "Stored Rows Rate",
     "type": "graph",
     "description": "per-second increasing rate of data flushed.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(milvus_datacoord_stored_rows_count{}[2m])/120) by (pod, node_id)",
       "legendFormat": "{{pod}}-{{node_id}}"
      }
     ]
    },
    {
     "title": "Segment Num",
     "type": "graph",
     "description": "Number of segments with different states in the Meta of DataCoord",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(milvus_datacoord_segment_num{}) by (segment_state)",
       "legendFormat": "{{segment_state}}"
      }
     ]
    },
    {
     "title": "Stored Binlog Size",
     "type": "graph",
     "description": "binlog size of all collections/segments, unit byte",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(milvus_datacoord_stored_binlog_size{}) by (app_kubernetes_io_instance)",
       "legendFormat": "size"
      }
     ]
    }
   ]
  },
  {
   "title": "Data Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Flowgraph Num",
     "type": "graph",
     "description": "Total number of flowgraph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(milvus_datanode_flowgraph_num{}) by (pod, node_id)",
       "legendFormat": "{{pod}}-{{node_id}}"
      }
     ]
    },
    {
     "title": "Producer Num",
     "type": "graph",
     "description": "Total number of prodecer created on the DataNode",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(milvus_datanode_producer_num{}) by (pod, node_id)",
       "legendFormat": "{{pod}}-{{node_id}}"
      }
     ]
    },
    {
     "title": "TimeTick Lag Behind Now (Consumed All)",
     "type": "graph",
     "description": "Average, maximum and minimum values of the  timestamps for time tick lag behind now.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg(milvus_datanode_consume_tt_lag_ms{msg_type=\"all\"}) by (pod, node_id)",
       "legendFormat": "{{pod}}-{{node_id}}-avg"
      },
      {
       "expr": "max(milvus_datanode_consume_tt_lag_ms{msg_type=\"all\"}) by (pod, node_id)",
       "legendFormat": "{{pod}}-{{node_id}}-max"
      },
      {
       "expr": "min(milvus_datanode_consume_tt_lag_ms{msg_type=\"all\"}) by (pod, node_id)",
       "legendFormat": "{{pod}}-{{node_id}}-min"
      }
     ]
    },
    {
     "title": "Produced TimeTick Lag Behind Now  For DC",
     "type": "graph",
     "description": "Average, maximum and minimum values of the  timestamps for time tick lag behind now, which send to DataCoord",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg(milvus_datanode_produce_tt_lag_ms{}) by (pod, node_id)",
       "legendFormat": "{{pod}}-{{node_id}}-avg"
      },
      {
       "expr": "max(milvus_datanode_produce_tt_lag_ms{}) by (pod, node_id)",
       "legendFormat": "{{pod}}-{{node_id}}-max"
      },
      {
       "expr": "min(milvus_datanode_produce_tt_lag_ms{}) by (pod, node_id)",
       "legendFormat": "{{pod}}-{{node_id}}-min"
      }
     ]
    },
    {
     "title": "Consumed Message Rate",
     "type": "graph",
     "description": "per-second increasing rate of consuming message",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(milvus_datanode_consume_msg_count{}[2m])/120) by (pod, node_id, msg_type)",
       "legendFormat": "{{pod}}-{{node_id}}-{{msg_type}}"
      }
     ]
    },
    {
     "title": "Consumed Message Rate",
     "type": "graph",
     "description": "per-second increasing rate of consuming message",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(milvus_datanode_consume_msg_count{}[2m])/120) by (pod, node_id)",
       "legendFormat": "{{pod}}-{{node_id}}"
      }
     ]
    },
    {
     "title": "Consumer Num",
     "type": "graph",
     "description": "Total number of consumers created on the DataNode",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(milvus_datanode_consumer_num{}) by (pod, node_id)",
       "legendFormat": "{{pod}}-{{node_id}}"
      }
     ]
    },
    {
     "title": "Encode Buffer Latency",
     "type": "graph",
     "description": "The 99th percentile and average latency of encode the data in the buffer over the last 2 minutes.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le, pod, node_id) (rate(milvus_datanode_encode_buffer_latency_bucket{}[2m])))",
       "legendFormat": "p99-{{pod}}-{{node_id}}"
      },
      {
       "expr": "sum(increase(milvus_datanode_encode_buffer_latency_sum{}[2m])) by(pod, node_id) / sum(increase(milvus_datanode_encode_buffer_latency_count{}[2m])) by(pod, node_id)",
       "legendFormat": "avg-{{pod}}-{{node_id}}"
      }
     ]
    },
    {
     "title": "Msg Rows Consumed Rate",
     "type": "graph",
     "description": "per-second increasing rate of messages consumed for insert and delete operation.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(milvus_datanode_msg_rows_count{}[2m])/120) by (msg_type, pod, node_id)",
       "legendFormat": "{{pod}}-{{node_id}}-{{msg_type}}"
      }
     ]
    },
    {
     "title": "Unflushed Segment Num",
     "type": "graph",
     "description": "Total number of segment that has been not flushed.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(milvus_datanode_unflushed_segment_num{}) by (pod, node_id)",
       "legendFormat": "{{pod}}-{{node_id}}"
      }
     ]
    },
    {
     "title": "Autoflush Operate Rate",
     "type": "graph",
     "description": "per-second increasing rate of auto flush operate.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(milvus_datanode_autoflush_buffer_op_count{}[2m])/120) by (status, pod, node_id)",
       "legendFormat": "{{pod}}-{{node_id}}-{{status}}"
      }
     ]
    },
    {
     "title": "Flush Data Size Rate",
     "type": "graph",
     "description": "per-second increasing rate of each message that has been flushed.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(milvus_datanode_flushed_data_size{}[2m])/120) by (msg_type, pod, node_id)",
       "legendFormat": "{{pod}}-{{node_id}}-{{msg_type}}"
      }
     ]
    },
    {
     "title": "Flush Operate Rate",
     "type": "graph",
     "description": "per-second increasing rate of flush operete.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(milvus_datanode_flush_buffer_op_count{}[2m])/120) by (status, pod, node_id)",
       "legendFormat": "{{pod}}-{{node_id}}-{{status}}"
      }
     ]
    },
    {
     "title": "Save Data Latency",
     "type": "graph",
     "description": "The 99th percentile and average latency of writte the data in buffer to storage  over the last 2 minutes.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le, pod, node_id) (rate(milvus_datanode_save_latency_bucket{}[2m])))",
       "legendFormat": "p99-{{pod}}-{{node_id}}"
      },
      {
       "expr": "sum(increase(milvus_datanode_save_latency_sum{}[2m])) by(pod, node_id) / sum(increase(milvus_datanode_save_latency_count{}[2m])) by(pod, node_id)",
       "legendFormat": "avg-{{pod}}-{{node_id}}"
      }
     ]
    },
    {
     "title": "Compaction Latency",
     "type": "graph",
     "description": "The 99th percentile and average latency of compaction over the last 2 minutes.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le, pod, node_id) (rate(milvus_datanode_compaction_latency_bucket{}[2m])))",
       "legendFormat": "p99-{{pod}}-{{node_id}}"
      },
      {
       "expr": "sum(increase(milvus_datanode_compaction_latency_sum{}[2m])) by(pod, node_id) / sum(increase(milvus_datanode_compaction_latency_count{}[2m])) by(pod, node_id)",
       "legendFormat": "avg-{{pod}}-{{node_id}}"
      }
     ]
    },
    {
     "title": "Flush Request Rate",
     "type": "graph",
     "description": "per-second increasing rate of flush requests.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(milvus_datanode_flush_req_count{}[2m])/120) by (status, pod, node_id)",
       "legendFormat": "{{pod}}-{{node_id}}-{{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Index Coordinator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Index Request Rate",
     "type": "graph",
     "description": "per-second increasing rate of building index requests received by IndexCoord.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(milvus_indexcoord_index_req_count{}[2m])/120) by (status)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Index Task Count",
     "type": "graph",
     "description": "Number of indexing tasks with different states in IndexCoord's meta",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(milvus_indexcoord_index_task_count{}) by (index_task_status)",
       "legendFormat": "{{index_task_status}}"
      }
     ]
    },
    {
     "title": "Index Node Num",
     "type": "graph",
     "description": "Number of index nodes which has register with etcd",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(milvus_indexcoord_index_node_num{}) by (app_kubernetes_io_instance)",
       "legendFormat": "total"
      }
     ]
    }
   ]
  },
  {
   "title": "Index Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Index Task Rate",
     "type": "graph",
     "description": "per-second increasing rate of index  tasks recevied by  IndexNode",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(milvus_indexnode_index_task_count{}[2m])/120) by (status, pod, node_id)",
       "legendFormat": "{{pod}}-{{node_id}}-{{status}}"
      }
     ]
    },
    {
     "title": "Load Field Latency",
     "type": "graph",
     "description": "The 99th percentile and average latency ofr load the FieldData over the last 2 minutes.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le, pod, node_id) (rate(milvus_indexnode_load_field_latency_bucket{}[2m])))",
       "legendFormat": "p99-{{pod}}-{{node_id}}"
      },
      {
       "expr": "sum(increase(milvus_indexnode_load_field_latency_sum{}[2m])) by(pod, node_id) / sum(increase(milvus_indexnode_load_field_latency_count{}[2m])) by(pod, node_id)",
       "legendFormat": "avg-{{pod}}-{{node_id}}"
      }
     ]
    },
    {
     "title": "Decode Field Latency",
     "type": "graph",
     "description": "The 99th percentile and average latency of decod the FieldData over the last 2 minutes.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le, pod, node_id) (rate(milvus_indexnode_decode_field_latency_bucket{}[2m])))",
       "legendFormat": "p99-{{pod}}-{{node_id}}"
      },
      {
       "expr": "sum(increase(milvus_indexnode_decode_field_latency_sum{}[2m])) by(pod, node_id) / sum(increase(milvus_indexnode_decode_field_latency_count{}[2m])) by(pod, node_id)",
       "legendFormat": "avg-{{pod}}-{{node_id}}"
      }
     ]
    },
    {
     "title": "Build Index Latency",
     "type": "graph",
     "description": "The 99th percentile and average latency of build index over the last 2 minutes.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le, pod, node_id) (rate(milvus_indexnode_build_index_latency_bucket{}[2m])))",
       "legendFormat": "p99-{{pod}}-{{node_id}}"
      },
      {
       "expr": "sum(increase(milvus_indexnode_build_index_latency_sum{}[2m])) by(pod, node_id) / sum(increase(milvus_indexnode_build_index_latency_count{}[2m])) by(pod, node_id)",
       "legendFormat": "avg-{{pod}}-{{node_id}}"
      }
     ]
    },
    {
     "title": "Encode Index Latency",
     "type": "graph",
     "description": "The 99th percentile and average latency of encode index over the last 2 minutes.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le, pod, node_id) (rate(milvus_indexnode_encode_index_latency_bucket{}[2m])))",
       "legendFormat": "p99-{{pod}}-{{node_id}}"
      },
      {
       "expr": "sum(increase(milvus_indexnode_encode_index_latency_sum{}[2m])) by(pod, node_id) / sum(increase(milvus_indexnode_encode_index_latency_count{}[2m])) by(pod, node_id)",
       "legendFormat": "avg-{{pod}}-{{node_id}}"
      }
     ]
    },
    {
     "title": "Save Index Latency",
     "type": "graph",
     "description": "The 99th percentile of latency for save index over the last 2 minutes.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le, pod, node_id) (rate(milvus_indexnode_save_index_latency_bucket{}[2m])))",
       "legendFormat": "p99-{{pod}}-{{node_id}}"
      },
      {
       "expr": "sum(increase(milvus_indexnode_save_index_latency_sum{}[2m])) by(pod, node_id) / sum(increase(milvus_indexnode_save_index_latency_count{}[2m])) by(pod, node_id)",
       "legendFormat": "avg-{{pod}}-{{node_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Usage Total",
     "type": "graph",
     "description": "Total cpu usage of all milvus components.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(process_cpu_seconds_total{}[5m]))",
       "legendFormat": "cpu usage"
      }
     ]
    },
    {
     "title": "Memory Total",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(process_resident_memory_bytes{})",
       "legendFormat": "memory"
      }
     ]
    },
    {
     "title": "Goroutines Total",
     "type": "graph",
     "description": "Number of goroutines that currently exist.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "sum(go_goroutines{})", "legendFormat": "goroutines" }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "process cpu usage",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{}[5m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "description": "Process memory of milvus pod.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 23 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "graph",
     "description": "Number of goroutines that currently exist.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "go_goroutines{}", "legendFormat": "{{pod}}" }
     ]
    },
    {
     "title": "Go Allocated Memory",
     "type": "graph",
     "description": "Number of bytes allocated and still in use.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      { "expr": "go_memstats_alloc_bytes{}", "legendFormat": "{{pod}}" }
     ]
    },
    {
     "title": "GC Max duration seconds",
     "type": "graph",
     "description": "GC Max duration seconds.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_gc_duration_seconds{quantile=\"1\", }",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "OS Threads",
     "type": "graph",
     "description": "Number of OS threads created.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "go_threads{}", "legendFormat": "{{pod}}" }
     ]
    },
    {
     "title": "Next GC Bytes",
     "type": "graph",
     "description": "Next GC Bytes.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      { "expr": "go_memstats_next_gc_bytes{}", "legendFormat": "{{pod}}" }
     ]
    },
    {
     "title": "Process Opened Fds",
     "type": "graph",
     "description": "Number of process opened fds.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "process_open_fds{}", "legendFormat": "{{pod}}" }
     ]
    },
    {
     "title": "GC CPU time",
     "type": "graph",
     "description": "The fraction of this program's available CPU time used by the GC since the program started.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "go_memstats_gc_cpu_fraction{}", "legendFormat": "{{pod}}" }
     ]
    },
    {
     "title": "Memory Free Rate",
     "type": "graph",
     "description": "Rate of memory frees.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_frees_total{}[5m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Go Memory mallocs rate.",
     "type": "graph",
     "description": "Rate of go memory mallocs.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_mallocs_total{}[2m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Allocated Heap Objects",
     "type": "graph",
     "description": "Number of allocated heap objects.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "go_memstats_heap_objects{}", "legendFormat": "{{pod}}" }
     ]
    },
    {
     "title": "Memory Allocated Rate",
     "type": "graph",
     "description": "Rate of bytes allocated, even if freed.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_alloc_bytes_total{}[5m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Go Heap released",
     "type": "graph",
     "description": "Number of heap bytes released to OS.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 47 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_released_bytes{}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Go Heap idle",
     "type": "graph",
     "description": "Number of heap bytes waiting to be used.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 47 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      { "expr": "go_memstats_heap_idle_bytes{}", "legendFormat": "{{pod}}" }
     ]
    },
    {
     "title": "Go Heap in Use",
     "type": "graph",
     "description": "Number of heap bytes that be used.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      { "expr": "go_memstats_heap_inuse_bytes{}", "legendFormat": "{{pod}}" }
     ]
    },
    {
     "title": "Container Threads",
     "type": "graph",
     "description": "Number of container threads created.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "container_threads{}" }
     ]
    }
   ]
  }
 ]
}