{
 "title": "dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "每分钟查询率",
   "type": "graph",
   "description": "条/分钟",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "query_vector_response_summary_count-(query_vector_response_summary_count offset 1m)"
    }
   ]
  },
  {
   "title": "并发连接数",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "connection_number" }
   ]
  },
  {
   "title": "运行时长",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    { "expr": "keeping_alive_seconds_total" }
   ]
  },
  {
   "title": "GPU_0_利用率",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "Gpu_usage_percent{DeviceNum=\"0\",instance=\"localhost:8080\",job=\"vecwise_server\"}"
    }
   ]
  },
  {
   "title": "GPU_1_利用率",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 6 },
   "targets": [
    {
     "expr": "Gpu_usage_percent{DeviceNum=\"1\",instance=\"localhost:8080\",job=\"vecwise_server\"}"
    }
   ]
  },
  {
   "title": "GPU_2_利用率",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "Gpu_usage_percent{DeviceNum=\"2\",instance=\"localhost:8080\",job=\"vecwise_server\"}"
    }
   ]
  },
  {
   "title": "GPU_3_利用率",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "Gpu_usage_percent{DeviceNum=\"3\",instance=\"localhost:8080\",job=\"vecwise_server\"}"
    }
   ]
  },
  {
   "title": "GPU_4_利用率",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "Gpu_usage_percent{DeviceNum=\"4\",instance=\"localhost:8080\",job=\"vecwise_server\"}"
    }
   ]
  },
  {
   "title": "GPU_5_利用率",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
   "targets": [
    {
     "expr": "Gpu_usage_percent{DeviceNum=\"5\",instance=\"localhost:8080\",job=\"vecwise_server\"}"
    }
   ]
  },
  {
   "title": "GPU_0显存使用量",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "GPU_memory_usage_total{DeviceNum=\"0\"}"
    }
   ]
  },
  {
   "title": "GPU_1显存使用量",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 11 },
   "targets": [
    {
     "expr": "GPU_memory_usage_total{DeviceNum=\"1\"}"
    }
   ]
  },
  {
   "title": "GPU_2显存使用量",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 11 },
   "targets": [
    {
     "expr": "GPU_memory_usage_total{DeviceNum=\"2\"}"
    }
   ]
  },
  {
   "title": "GPU_3显存使用量",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "GPU_memory_usage_total{DeviceNum=\"3\"}"
    }
   ]
  },
  {
   "title": "GPU_4显存使用量",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 11 },
   "targets": [
    {
     "expr": "GPU_memory_usage_total{DeviceNum=\"4\"}"
    }
   ]
  },
  {
   "title": "GPU_5显存使用量",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 11 },
   "targets": [
    {
     "expr": "GPU_memory_usage_total{DeviceNum=\"5\"}"
    }
   ]
  },
  {
   "title": "缓存利用率",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "cache_usage_bytes" }
   ]
  },
  {
   "title": "CPU利用率",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "CPU_usage_percent" }
   ]
  },
  {
   "title": "内存利用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "RAM_usage_percent" }
   ]
  },
  {
   "title": "查询响应时间",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "query_response_summary/1e6" }
   ]
  },
  {
   "title": "数据文件总量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "data_file_size_bytes" }
   ]
  },
  {
   "title": "网络IO",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    { "expr": "octets_bytes_per_second" }
   ]
  },
  {
   "title": "磁盘写速度",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "disk_store_IO_speed_bytes_per_microseconds*1e6"
    }
   ]
  },
  {
   "title": "磁盘读速度",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "disk_load_IO_speed_byte_per_microsec*1e6"
    }
   ]
  },
  {
   "title": "数据插入速度",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "add_vectors_throughput_per_microsecond*(1e6)"
    }
   ]
  },
  {
   "title": "数据总量",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "add_vectors_request_total" }
   ]
  }
 ]
}