name: 🚀 Change request
description: Want to add something new? Suggest an idea for this Doc
labels: []
assignees:
 Enter Assign Here
body:
- type: markdown
  attributes:
    value: |
      > Note: This repository is ONLY used to solve issues related to DOCS.
      > For other issues, please move to [other repositories](https://github.com/milvus-io/).

- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue related to this feature request already exists.
    options:
    - label: I have searched the existing issues
      required: true
      
- type: textarea
  attributes:
    label: Is there anything that's missing or inappropriate in the docs? Please describe.
    description: Describe what the problem is, and where is it. Ex. I think it's better to add/change [...] in [Install Milvus].
  validations:
    required: true
    
- type: textarea
  attributes:
    label: Describe your suggestion.
    description: A clear and concise description of what you want to change or add.
  validations:
    required: false
    
- type: textarea
  attributes:
    label: Additional reference.
    description: Provide any other reference docs or websites about your request.
  validations:
    required: false
