name: Trigger milvus.io preview build

on:
  repository_dispatch:
    types: [prod-deploy]
  push:
    branches:
      - preview
    paths-ignore:
      - "preview/**.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Yarn install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Generate EN Docs
        run: |
          git config --global user.email "Milvus-doc-bot@zilliz.com"
          git config --global user.name "Milvus-doc-bot"
          touch .env
          echo DEEPL_API_KEY=${{secrets.DEEPL_API_KEY}} >> .env
          echo GITHUB_TOKEN=${{secrets.GH_TOKEN}} >> .env
          yarn generate:en

      - name: Commit and push
        run: |
          git add .
          git commit -m "Generate en docs"
          git push -f origin preview
        continue-on-error: true

      - name: Trigger milvus.io preview
        run: |
          curl -XPOST -H "Authorization: Bearer ${{secrets.GH_TOKEN}}" https://api.github.com/repos/milvus-io/milvus.io/actions/workflows/preview_aws.yml/dispatches -d '{"ref": "preview"}'
